# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files and tsconfig for build
COPY package.json tsconfig.json ./

# Copy source code
COPY src ./src

# Install all dependencies ignoring peer conflicts, then build
RUN npm install --ignore-scripts --legacy-peer-deps && npm run build

# Command to run the MCP server over stdio
CMD ["node", "build/stdio.js"]
